name: gl4dius-stack

services:
  gl4dius:
    image: gl4dius-dev:latest
    build:
      context: .
      dockerfile: misc/installation/dev-env/Dockerfile
    container_name: gl4dius
    working_dir: /app
    volumes:
      - ./cli/target:/app
      - ./misc/installation/dev-env/template:/home/gl4dius/template/
      - ./misc/installation/dev-env/.gl4dius.db:/home/gl4dius/.gl4dius.db
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: false
    stdin_open: true
    tty: true
    command: /bin/bash
    networks:
      gl4dius-lab:
        ipv4_address: 172.28.0.10

  victim:
    image: linuxserver/webtop:debian-mate-version-71d1c861
    container_name: victim
    command: sleep infinity
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - "3000:3000"
      - "5900:5900"
    shm_size: "2gb"
    networks:
      gl4dius-lab:
        ipv4_address: 172.28.0.20

networks:
  gl4dius-lab:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24
