spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

gl4dius:
  cli:
    prompt:
      key: Gl4dius
  database:
    file-name: .gl4dius.db
